version: "3.9"
   
services:
    db:
        build:
            context: ./api/postgresql
            dockerfile: Postgresql.Dockerfile
        environment: 
            - POSTGRES_DB=myproject
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./data/db:/var/lib/postgresql/data

    api:
        build:
            context: ./api/
            dockerfile: Django.Dockerfile
        command: bash django-entrypoint.sh
        volumes:
            - ./api:/api
        ports:
            - "8000:8000"
        depends_on:
            - db

    client:
        build:
            context: ./client/
            dockerfile: Quasar.Dockerfile
        command: quasar dev
        volumes:
            - ./client:/client
        ports:
            - "8080:8080"
        depends_on:
            - api