version: "3.9"
   
services:
    db:
        container_name: db
        restart: always
        build:
            context: ./api/postgresql
            dockerfile: Postgresql.Dockerfile
        ports:
            - 5432:5432
        env_file: 
            .env
        volumes:
            - ./data/db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h db -U myuser"]
            interval: 10s
            timeout: 5s
            retries: 5

    api:
        container_name: api
        build:
            context: ./api/
            dockerfile: Django.Dockerfile
        command: bash django-entrypoint.sh
        ports:
            - 8000:8000
        env_file: 
            .env
        volumes:
            - ./api:/api
        depends_on:
            - db
        links:
            - db:db

    client:
        container_name: client
        build:
            context: ./client/
            dockerfile: Quasar.Dockerfile
        command: quasar dev
        volumes:
            - ./client:/client
            - /client/node_modules
        ports:
            - 8080:8080
        depends_on:
            - api