name: Python CI

on:
  push:
    branches:
      - master
    paths:
      - api/**
  pull_request:
    paths:
      - api/**

jobs:
  build_and_test_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build api container
      run: docker-compose up --build -d db api
    - name: Run api lint
      run: docker-compose run api bash -c "pylint --load-plugins pylint_django --django-settings-module=api.settings --fail-under=5 ./**/*.py" 
    - name: Run api tests
      run: docker-compose run api coverage run --source="." --omit="manage.py" manage.py test
    - name: Check coverage
      run: docker-compose run api coverage report --fail-under=80
  
  # coverage:
  #   needs: [ build_and_test ]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: paambaati/codeclimate-action@v2.7.5
  #     env:
  #       CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
  #     with:
  #       coverageLocations: |
  #         ${{github.workspace}}/api/*
  #       debug: true
  