name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - api/**
  pull_request:
    paths:
      - api/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build api container
      run: docker-compose up -d api
    - name: run api tests
      run: docker-compose run api python manage.py test