name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - api/**
  pull_request:
    paths:
      - api/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build api container
      run: docker-compose up -d api