name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - api/**
  pull_request:
    paths:
      - api/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build api container
      run: docker-compose up --build -d api
    - name: run api tests
      run: docker-compose run api coverage run --source='.' manage.py test
  
  coverage:
    needs: [ build_and_test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          ${{github.workspace}}/*.coverage:coverage
        debug: true
  