name: Python CI

on:
  push:
    branches:
      - master
    paths:
      - api/**
  pull_request:
    paths:
      - api/**

jobs:
  build_and_test_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build api container
      run: docker-compose up --build -d db api
    - name: list services
<<<<<<< HEAD
      run: docker-compose ps --services && docker-compose ps && docker ps
=======
      run: docker-compose ps --services && docker-compose ps && docker ps -a
>>>>>>> 04b23d41db2f005a58980c32524d72834f5efb53
    - name: cat settings
      run: docker-compose run api cat api/settings.py 
    - name: run api tests
      run: docker-compose run api coverage run --source='.' manage.py test
  
  # coverage:
  #   needs: [ build_and_test ]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: paambaati/codeclimate-action@v2.7.5
  #     env:
  #       CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
  #     with:
  #       coverageLocations: |
  #         ${{github.workspace}}/api/*
  #       debug: true
  