name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - client/**
  pull_request:
    paths:
      - client/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build client container
      run: docker-compose up --build -d client
    - name: run client tests
      run: docker-compose run client quasar test --unit jest
  
  coverage:
    needs: [ build_and_test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          ${{github.workspace}}/test/jest/coverage/*.json:json
        debug: true