name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - api/**
  pull_request:
    paths:
      - api/**

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build client container
      run: docker-compose up -d client
    - name: run client tests
      run: docker-compose run client quasar test --unit jest