name: Coverage

on:
  workflow_run:
    workflows: ["Node.js CI", "Python CI"]
    types: [completed]
    branches: [master]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          ${{github.workspace}}/client/test/jest/coverage/*:lcov
          ${{github.workspace}}/api/*:coverage.py
        debug: true