name: Coverage

on:
  push:
    branches:
      - master
  # workflow_run:
  #   workflows: ["Node.js CI", "Python CI"]
  #   types: [completed]
  #   branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose up --build -d db api
    # - name: test
    #   run: docker-compose run api coverage run manage.py test
    # - name: generate xml
    #   run: docker-compose run api coverage xml
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: S{{ secrets.TEST_REPORTER_ID }}
      with:
        coverageCommand: docker-compose run api bash -c "coverage run manage.py test && coverage xml"
        coverageLocations: |
          ${{github.workspace}}/api/*.xml:coverage.py
