name: Coverage

on:
  push:
    branches:
      - master
  # workflow_run:
  #   workflows: ["Node.js CI", "Python CI"]
  #   types: [completed]
  #   branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose up --build -d db api
    - name: Setup Code Climate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Initialize Code Climate test reporter
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
        GIT_BRANCH=$GITHUB_HEAD_REF GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF) ./cc-test-reporter before-build
    - name: test
      run: docker-compose run api coverage run manage.py test
    - name: generate xml
      run: docker-compose run api coverage xml
    - name: Send test report to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      run: |
        GIT_BRANCH=$GITHUB_HEAD_REF GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF) ./cc-test-reporter after-build --exit-code $?
