name: Coverage

on:
  push:
    branches:
      - master
  # workflow_run:
  #   workflows: ["Node.js CI", "Python CI"]
  #   types: [completed]
  #   branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose up --build -d db api
    - name: test
      run: docker-compose run api coverage run manage.py test
    - name: generate xml
      run: docker-compose run api coverage xml
    - name: debug
      run: echo ${{github.workspace}} && ls ${{github.workspace}}/api/
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      with:
          # ${{github.workspace}}/client/test/jest/coverage/lcov.info:lcov
        coverageLocations: |
          ${{github.workspace}}/api/coverage.xml:coverage.py
        debug: true