name: Coverage

on:
  push:
    branches:
      - master
  # workflow_run:
  #   workflows: ["Node.js CI", "Python CI"]
  #   types: [completed]
  #   branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose up --build -d db api
    - name: test
      run: docker-compose run api coverage run manage.py test
    - name: generate xml
      run: docker-compose run api coverage xml
    - uses: codecov/codecov-action@v1
      with:
        files: ${{github.workspace}}/api/coverage.xml
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)